---
enabled_features:
- lldp
- ospf
- bgp
- lacp
- pim
- vn-segment-vlan-based
- nv overlay
- fabric forwarding
- interface-vlan
- bfd

special_features:
- nv overlay evpn

loopbacks:
  - name: loopback0
    description: "Router ID"
    enabled: true
  - name: loopback1
    description: "BGP-EVPN int"
    enabled: true

loopback_ips:
  - name: loopback0
    ipv4:
      address: "10.10.10.{{ ansible host.split(.)[3] }}"
  - name: loopback1
    ipv4:
      address: "20.20.20.{{ ansible_host.split(.)[3] }}"