---
# LAG Interface Configuration for nxos_lag_interfaces
lag_interfaces:
  - name: port-channel411
    members:
      - member: Ethernet1/1
        mode: active
      - member: Ethernet1/2
        mode: active
  - name: port-channel412
    members:
      - member: Ethernet1/3
        mode: active
      - member: Ethernet1/4
        mode: active
  - name: port-channel421
    members:
      - member: Ethernet1/5
        mode: active
      - member: Ethernet1/6
        mode: active
  - name: port-channel422
    members:
      - member: Ethernet1/7
        mode: active
      - member: Ethernet1/8
        mode: active
  - name: port-channel431
    members:
      - member: Ethernet1/9
        mode: active
      - member: Ethernet1/10
        mode: active
  - name: port-channel432
    members:
      - member: Ethernet1/11
        mode: active
      - member: Ethernet1/12
        mode: active

# L3 Interface Configuration for nxos_l3_interfaces
l3_interfaces:
  - name: port-channel411
    ipv4:
      - address: 30.30.30.73/30
  - name: port-channel412
    ipv4:
      - address: 30.30.30.77/30
  - name: port-channel421
    ipv4:
      - address: 30.30.30.81/30
  - name: port-channel422
    ipv4:
      - address: 30.30.30.85/30
  - name: port-channel431
    ipv4:
      - address: 30.30.30.89/30
  - name: port-channel432
    ipv4:
      - address: 30.30.30.93/30

# Interface Configuration for nxos_interfaces
interfaces:
  - name: port-channel411
    description: "Downlink to dub-st1-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel412
    description: "Downlink to dub-st1-sp2"
    mtu: 9216
    enabled: true
  - name: port-channel421
    description: "Downlink to dub-st2-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel422
    description: "Downlink to dub-st2-sp2"
    mtu: 9216
    enabled: true
  - name: port-channel431
    description: "Downlink to dub-st3-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel432
    description: "Downlink to dub-st3-sp2"
    mtu: 9216
    enabled: true
