---
# LAG Interface Configuration for nxos_lag_interfaces
lag_interfaces:
  - name: port-channel311
    members:
      - member: Ethernet1/1
        mode: active
      - member: Ethernet1/2
        mode: active
  - name: port-channel312
    members:
      - member: Ethernet1/3
        mode: active
      - member: Ethernet1/4
        mode: active
  - name: port-channel321
    members:
      - member: Ethernet1/5
        mode: active
      - member: Ethernet1/6
        mode: active
  - name: port-channel322
    members:
      - member: Ethernet1/7
        mode: active
      - member: Ethernet1/8
        mode: active
  - name: port-channel331
    members:
      - member: Ethernet1/9
        mode: active
      - member: Ethernet1/10
        mode: active
  - name: port-channel332
    members:
      - member: Ethernet1/11
        mode: active
      - member: Ethernet1/12
        mode: active

# L3 Interface Configuration for nxos_l3_interfaces
l3_interfaces:
  - name: port-channel311
    ipv4:
      - address: 30.30.30.49/30
  - name: port-channel312
    ipv4:
      - address: 30.30.30.53/30
  - name: port-channel321
    ipv4:
      - address: 30.30.30.57/30
  - name: port-channel322
    ipv4:
      - address: 30.30.30.61/30
  - name: port-channel331
    ipv4:
      - address: 30.30.30.65/30
  - name: port-channel332
    ipv4:
      - address: 30.30.30.69/30

# Interface Configuration for nxos_interfaces
interfaces:
  - name: port-channel311
    description: "Downlink to dub-st1-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel312
    description: "Downlink to dub-st1-sp2"
    mtu: 9216
    enabled: true
  - name: port-channel321
    description: "Downlink to dub-st2-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel322
    description: "Downlink to dub-st2-sp2"
    mtu: 9216
    enabled: true
  - name: port-channel331
    description: "Downlink to dub-st3-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel332
    description: "Downlink to dub-st3-sp2"
    mtu: 9216
    enabled: true
