---
lag_interfaces:
  - name: port-channel3131
    members:
      - member: Ethernet1/1
        mode: active
      - member: Ethernet1/2
        mode: active
  - name: port-channel3231
    members:
      - member: Ethernet1/3
        mode: active
      - member: Ethernet1/4
        mode: active

l3_interfaces:
  - name: port-channel3131
    ipv4:
      - address: 30.30.30.131/30
  - name: port-channel3231
    ipv4:
      - address: 30.30.30.139/30

interfaces:
  - name: port-channel3131
    description: "Uplink to dub-st3-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel3231
    description: "Uplink to dub-st3-sp2"
    mtu: 9216
    enabled: true

