---
lag_interfaces:
  - name: port-channel2111
    members:
      - member: Ethernet1/1
        mode: active
      - member: Ethernet1/2
        mode: active
  - name: port-channel2112
    members:
      - member: Ethernet1/3
        mode: active
      - member: Ethernet1/4
        mode: active

l3_interfaces:
  - name: port-channel2111
    ipv4:
      - address: 30.30.30.114/30
  - name: port-channel2112
    ipv4:
      - address: 30.30.30.122/30

interfaces:
  - name: port-channel2111
    description: "Uplink to dub-st2-sp1"
    mtu: 9216
    enabled: true
  - name: port-channel2112
    description: "Uplink to dub-st2-sp2"
    mtu: 9216
    enabled: true
