---
# LAG Interface Configuration for nxos_lag_interfaces
lag_interfaces:
  - name: port-channel111
    members:
      - member: Ethernet1/1
        mode: active
      - member: Ethernet1/2
        mode: active
  - name: port-channel211
    members:
      - member: Ethernet1/3
        mode: active
      - member: Ethernet1/4
        mode: active
  - name: port-channel311
    members:
      - member: Ethernet1/5
        mode: active
      - member: Ethernet1/6
        mode: active
  - name: port-channel411
    members:
      - member: Ethernet1/7
        mode: active
      - member: Ethernet1/8
        mode: active
  - name: port-channel1211
    members:
      - member: Ethernet1/9
        mode: active
      - member: Ethernet1/10
        mode: active
  - name: port-channel1212
    members:
      - member: Ethernet1/11
        mode: active
      - member: Ethernet1/12
        mode: active

# L3 Interface Configuration for nxos_l3_interfaces
l3_interfaces:
  - name: port-channel111
    ipv4:
      - address: 30.30.30.6/30
  - name: port-channel211
    ipv4:
      - address: 30.30.30.30/30
  - name: port-channel311
    ipv4:
      - address: 30.30.30.54/30
  - name: port-channel411
    ipv4:
      - address: 30.30.30.78/30
  - name: port-channel1211
    ipv4:
      - address: 30.30.30.105/30
  - name: port-channel1212
    ipv4:
      - address: 30.30.30.109/30

# Interface Configuration for nxos_interfaces
interfaces:
  - name: port-channel111
    description: "Uplink to dub-ssp1"
    mtu: 9216
    enabled: true
  - name: port-channel211
    description: "Uplink to dub-ssp2"
    mtu: 9216
    enabled: true
  - name: port-channel311
    description: "Uplink to dub-ssp3"
    mtu: 9216
    enabled: true
  - name: port-channel411
    description: "Uplink to dub-ssp4"
    mtu: 9216
    enabled: true
  - name: port-channel1211
    description: "Downlink to dub-st1-lf1"
    mtu: 9216
    enabled: true
  - name: port-channel1212
    description: "Downlink to dub-st1-lf2"
    mtu: 9216
    enabled: true
