---
- name: LAG Configuration with Cleanup and MTU Fix
  hosts: data_switches
  gather_facts: false
  vars:
    template: "{{ playbook_dir }}/../templates/data_switches.yml"

  tasks:
    - name: Enable required features
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
      loop: "{{ enabled_features }}"
      tags: features

    - name: Enable nv overlay evpn
      cisco.nxos.nxos_evpn_global:
        nv_overlay_evpn: true

    - name: Set MTU on member interfaces to 9216
      cisco.nxos.nxos_config:
        lines:
          - "mtu 9216"
        parents: "interface {{ item.1.member }}"
        save_when: modified
      with_subelements:
        - "{{ lag_interfaces }}"
        - members
      tags: interfaces

    - name: Configure port-channels and member interfaces
      cisco.nxos.nxos_lag_interfaces:
        config: "{{ lag_interfaces }}"
        state: merged
      tags: interfaces

    - name: Configure interface properties (port-channels and members)
      cisco.nxos.nxos_interfaces:
        config: "{{ interfaces }}"
        state: merged
      tags: interfaces

    - name: Configure routed interfaces (IP addresses)
      cisco.nxos.nxos_l3_interfaces:
        config: "{{ l3_interfaces }}"
        state: merged
      tags: interfaces

    - name: Save configuration
      cisco.nxos.nxos_config:
        save_when: always
      tags: config

