---
- name: Configure loopbacks with IP addresses
  hosts: data_switches
  gather_facts: false

  tasks:
    - name: Up loopback interface, set description
      cisco.nxos.nxos_interfaces: 
        config:
          - name: "{{ loopbacks }}"
    
    - name: Assign IP address to loopback
      cisco.nxos.nxos_l3_interfaces:
        config: "{{ loopback_ips }}"

    
      
      


