---
- name: Generate NX-OS config files via template
  hosts: data_switches
  tasks:
    - name: Generate config from template
      template:
        src: "{{ playbook_dir }}/../templates/data_switches_template.j2"
        dest: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}.cfg"
        
    - name: Append timestamp comment to config file
      shell: echo "#Config created via Jinja template on $(date -Iseconds)." >> "{{ playbook_dir }}/../configs/{{ inventory_hostname }}_cfg.txt"
