---
- name: Generate NX-OS config files via template
  hosts: data_switches
  tasks:
    - name: Generate config from template
      template:
        src: data_switch_template.j2
        dest: ./configs/{{ inventory_hostname }}_cfg.txt

    - name: Append timestamp comment to config file
      lineinfile:
        path: ./configs/{{ inventory_hostname }}_cfg.txt
        line: "#Config created via Jinja template on {{ ansible_date_time.iso8601 }}."
        insertafter: EOF